name: Build and Deploy
on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 6.23.5
        run_install: true
    # - name: Install
    #   run: npm install
    - name: ESLint
      run: pnpm run lint:js
    - name: Templates
      run: pnpm run lint:hbs

  # coverage:
  #   name: Coverage
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [12.x]
  #   if: "!contains(github.event.head_commit.message, 'skip ci')"
  #   steps:

  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}

    - name: Run coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
      run: |
        # npm install
        pnpm run test:ember
    - name: Coveralls action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  # tests_ember_compat:
  #   name: Ember Compatability
  #   runs-on: ubuntu-latest
  #   if: "!contains(github.event.head_commit.message, 'skip ci')"
  #   strategy:
  #     matrix:
  #       node-version: [12.x]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - name: Install
  #     run: npm install
    - name: Test
      run: pnpm run test:ember

  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   if: "!contains(github.event.head_commit.message, 'skip ci')"
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0
  #   - name: Node setup
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: 14
    - name: Build
      run: |
        # npm install
        pnpm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: pnpm run semantic-release
