name: Pull Request
on:
  - pull_request

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
            path: ~/.pnpm-store
            key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
                ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.23.5
      - name: Install
        run: pnpm install
        working-directory: .
      - name: ESLint Addon
        run: pnpm run lint:js
        working-directory: ./addon
      - name: Template Lint Addon
        run: pnpm run lint:hbs
        working-directory: ./addon
      - name: ESLint Test App
        run: pnpm run lint:js
        working-directory: ./test-app
      - name: Template Lint Test App
        run: pnpm run lint:hbs
        working-directory: ./test-app
      - run: pnpm run test:ember
        working-directory: ./test-app

